-- Allow a contact to be associated with multiple companies, optionally with
-- the month and year in which the affiliation started and ended.
create table public.contact_companies (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    company_id bigint not null,
    start_date date,
    end_date date,
    constraint contact_companies_month_only check (
        (start_date is null or extract(day from start_date) = 1)
        and (end_date is null or extract(day from end_date) = 1)
    ),
    constraint contact_companies_date_order check (
        start_date is null or end_date is null or start_date <= end_date
    ),
    constraint contact_companies_contact_company_unique unique (contact_id, company_id),
    constraint contact_companies_contact_id_fkey foreign key (contact_id)
        references public.contacts(id) on update cascade on delete cascade,
    constraint contact_companies_company_id_fkey foreign key (company_id)
        references public.companies(id) on update cascade on delete cascade
);

create index contact_companies_contact_id_idx
    on public.contact_companies using btree (contact_id);
create index contact_companies_company_id_idx
    on public.contact_companies using btree (company_id);

alter table public.contact_companies enable row level security;

create policy "Enable read access for authenticated users"
    on public.contact_companies for select to authenticated using (true);
create policy "Enable insert for authenticated users only"
    on public.contact_companies for insert to authenticated with check (true);
create policy "Enable update for authenticated users only"
    on public.contact_companies for update to authenticated using (true) with check (true);
create policy "Contact Company Delete Policy"
    on public.contact_companies for delete to authenticated using (true);

grant all on table public.contact_companies to anon;
grant all on table public.contact_companies to authenticated;
grant all on table public.contact_companies to service_role;
grant all on sequence public.contact_companies_id_seq to anon;
grant all on sequence public.contact_companies_id_seq to authenticated;
grant all on sequence public.contact_companies_id_seq to service_role;

drop view public.contacts_summary;

create view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', cc.id,
                'contact_id', cc.contact_id,
                'company_id', cc.company_id,
                'start_date', cc.start_date,
                'end_date', cc.end_date
            ) order by cc.start_date nulls last, cc.id
        ) filter (where cc.id is not null),
        '[]'::jsonb
    ) as company_affiliations,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
    left join public.contact_companies cc on co.id = cc.contact_id
group by co.id, c.name;

grant all on table public.contacts_summary to anon;
grant all on table public.contacts_summary to authenticated;
grant all on table public.contacts_summary to service_role;

create or replace view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
        or exists (
            select 1
            from public.contact_companies cc
            where cc.contact_id = co.id and cc.company_id = c.id
        )
group by c.id;
